<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.551">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Nicolas Grosse">

<title>Classification de clients</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="projetada_files/libs/clipboard/clipboard.min.js"></script>
<script src="projetada_files/libs/quarto-html/quarto.js"></script>
<script src="projetada_files/libs/quarto-html/popper.min.js"></script>
<script src="projetada_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="projetada_files/libs/quarto-html/anchor.min.js"></script>
<link href="projetada_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="projetada_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="projetada_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="projetada_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="projetada_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Classification de clients</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Nicolas Grosse </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="problématique" class="level2">
<h2 class="anchored" data-anchor-id="problématique">Problématique</h2>
<p>Un directeur de supermarché souhaite augmenter son chiffre d’affaire en ciblant plus efficacement les campagnes promotionnellesdu magasin. Il consulte donc le service marketing, où nous travaillons en tant que data scientist , afin de mieux connaître sa clientèle et de regrouper les clients en cluster pour les futurs opérations marketing.</p>
<p>Nous disposons pour cela d’un jeu de données sur les habitudes d’achats et les informations personnelles de 2240 clients du supermarché qui disposent d’une carte de fidélité qui nous permet de suivre leur dépenses.</p>
</section>
<section id="importation-et-présentation-des-données" class="level2">
<h2 class="anchored" data-anchor-id="importation-et-présentation-des-données">1. Importation et présentation des données</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(FactoMineR)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(factoextra)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(cluster)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggpubr) <span class="co"># fonctions ggboxplot ggscatter</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caret)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(NbClust)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gridExtra)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyselect)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pastecs) <span class="co"># fonction stat.desc</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"marketing_campaign.csv"</span>, <span class="at">sep =</span> <span class="st">"</span><span class="sc">\t</span><span class="st">"</span>, <span class="at">row.names =</span> <span class="dv">1</span>, <span class="at">stringsAsFactors =</span> <span class="cn">TRUE</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span><span class="fu">c</span>(Dt_Customer,Z_CostContact,Z_Revenue,Complain,Response)) <span class="co"># les variables Z_CostContact et Z_Revenue sont constantes et sont donc supprimées, les variables Response et Complain concernent peu de clients et sont donc aussi supprimées</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> <span class="fu">rename</span>(<span class="at">Wine =</span> MntWines, <span class="at">Fruits =</span> MntFruits, <span class="at">Meat =</span> MntMeatProducts, <span class="at">Fish =</span> MntFishProducts, <span class="at">Sweets =</span> MntSweetProducts, <span class="at">Gold =</span> MntGoldProds)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Year_Birth"          "Education"           "Marital_Status"     
 [4] "Income"              "Kidhome"             "Teenhome"           
 [7] "Recency"             "Wine"                "Fruits"             
[10] "Meat"                "Fish"                "Sweets"             
[13] "Gold"                "NumDealsPurchases"   "NumWebPurchases"    
[16] "NumCatalogPurchases" "NumStorePurchases"   "NumWebVisitsMonth"  
[19] "AcceptedCmp3"        "AcceptedCmp4"        "AcceptedCmp5"       
[22] "AcceptedCmp1"        "AcceptedCmp2"       </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2240   23</code></pre>
</div>
</div>
<p>Notre jeu de données est composée de 23 variables décrivant 2240 clients.</p>
<p>Les six premières variables sont des informations personnelles sur les clients : l’année de naissance, le niveau d’éducation, l’état matrimonial, le revenu annuel, le nombre d’enfants à charge et le nombre d’adolescents à charge.</p>
<p>La variable Recency correspond au nombre de jours depuis le dernier achat.</p>
<p>Les six variables suivantes sont toutes quantitatives et sont les dépenses de chaque client dans diverses catégories de produit : le vin, les fruits, la viande, le poisson, les sucreries, et les bijoux (Gold). Nous trouvons ensuite le nombre d’achats d’articles en promotion, le nombre d’achats par internet, le nombre d’achats par catalogue, le nombre d’achats en magasin, ainsi que le nombre de visites sur le site web du magasin.</p>
<p>Les cinq dernières variables sont binaires et représentent l’acceptation ou non d’une offre durant chacune des cinq dernières campagnes promotionnelles.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   2240 obs. of  23 variables:
 $ Year_Birth         : int  1957 1954 1965 1984 1981 1967 1971 1985 1974 1950 ...
 $ Education          : Factor w/ 5 levels "2n Cycle","Basic",..: 3 3 3 3 5 4 3 5 5 5 ...
 $ Marital_Status     : Factor w/ 8 levels "Absurd","Alone",..: 5 5 6 6 4 6 3 4 6 6 ...
 $ Income             : int  58138 46344 71613 26646 58293 62513 55635 33454 30351 5648 ...
 $ Kidhome            : int  0 1 0 1 1 0 0 1 1 1 ...
 $ Teenhome           : int  0 1 0 0 0 1 1 0 0 1 ...
 $ Recency            : int  58 38 26 26 94 16 34 32 19 68 ...
 $ Wine               : int  635 11 426 11 173 520 235 76 14 28 ...
 $ Fruits             : int  88 1 49 4 43 42 65 10 0 0 ...
 $ Meat               : int  546 6 127 20 118 98 164 56 24 6 ...
 $ Fish               : int  172 2 111 10 46 0 50 3 3 1 ...
 $ Sweets             : int  88 1 21 3 27 42 49 1 3 1 ...
 $ Gold               : int  88 6 42 5 15 14 27 23 2 13 ...
 $ NumDealsPurchases  : int  3 2 1 2 5 2 4 2 1 1 ...
 $ NumWebPurchases    : int  8 1 8 2 5 6 7 4 3 1 ...
 $ NumCatalogPurchases: int  10 1 2 0 3 4 3 0 0 0 ...
 $ NumStorePurchases  : int  4 2 10 4 6 10 7 4 2 0 ...
 $ NumWebVisitsMonth  : int  7 5 4 6 5 6 6 8 9 20 ...
 $ AcceptedCmp3       : int  0 0 0 0 0 0 0 0 0 1 ...
 $ AcceptedCmp4       : int  0 0 0 0 0 0 0 0 0 0 ...
 $ AcceptedCmp5       : int  0 0 0 0 0 0 0 0 0 0 ...
 $ AcceptedCmp1       : int  0 0 0 0 0 0 0 0 0 0 ...
 $ AcceptedCmp2       : int  0 0 0 0 0 0 0 0 0 0 ...</code></pre>
</div>
</div>
<p>Caculons quelques statistiques descriptives pour chaque variable :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Year_Birth        Education     Marital_Status     Income      
 Min.   :1893   2n Cycle  : 203   Married :864    Min.   :  1730  
 1st Qu.:1959   Basic     :  54   Together:580    1st Qu.: 35303  
 Median :1970   Graduation:1127   Single  :480    Median : 51382  
 Mean   :1969   Master    : 370   Divorced:232    Mean   : 52247  
 3rd Qu.:1977   PhD       : 486   Widow   : 77    3rd Qu.: 68522  
 Max.   :1996                     Alone   :  3    Max.   :666666  
                                  (Other) :  4    NA's   :24      
    Kidhome          Teenhome         Recency           Wine        
 Min.   :0.0000   Min.   :0.0000   Min.   : 0.00   Min.   :   0.00  
 1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:24.00   1st Qu.:  23.75  
 Median :0.0000   Median :0.0000   Median :49.00   Median : 173.50  
 Mean   :0.4442   Mean   :0.5062   Mean   :49.11   Mean   : 303.94  
 3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:74.00   3rd Qu.: 504.25  
 Max.   :2.0000   Max.   :2.0000   Max.   :99.00   Max.   :1493.00  
                                                                    
     Fruits           Meat             Fish            Sweets      
 Min.   :  0.0   Min.   :   0.0   Min.   :  0.00   Min.   :  0.00  
 1st Qu.:  1.0   1st Qu.:  16.0   1st Qu.:  3.00   1st Qu.:  1.00  
 Median :  8.0   Median :  67.0   Median : 12.00   Median :  8.00  
 Mean   : 26.3   Mean   : 166.9   Mean   : 37.53   Mean   : 27.06  
 3rd Qu.: 33.0   3rd Qu.: 232.0   3rd Qu.: 50.00   3rd Qu.: 33.00  
 Max.   :199.0   Max.   :1725.0   Max.   :259.00   Max.   :263.00  
                                                                   
      Gold        NumDealsPurchases NumWebPurchases  NumCatalogPurchases
 Min.   :  0.00   Min.   : 0.000    Min.   : 0.000   Min.   : 0.000     
 1st Qu.:  9.00   1st Qu.: 1.000    1st Qu.: 2.000   1st Qu.: 0.000     
 Median : 24.00   Median : 2.000    Median : 4.000   Median : 2.000     
 Mean   : 44.02   Mean   : 2.325    Mean   : 4.085   Mean   : 2.662     
 3rd Qu.: 56.00   3rd Qu.: 3.000    3rd Qu.: 6.000   3rd Qu.: 4.000     
 Max.   :362.00   Max.   :15.000    Max.   :27.000   Max.   :28.000     
                                                                        
 NumStorePurchases NumWebVisitsMonth  AcceptedCmp3      AcceptedCmp4    
 Min.   : 0.00     Min.   : 0.000    Min.   :0.00000   Min.   :0.00000  
 1st Qu.: 3.00     1st Qu.: 3.000    1st Qu.:0.00000   1st Qu.:0.00000  
 Median : 5.00     Median : 6.000    Median :0.00000   Median :0.00000  
 Mean   : 5.79     Mean   : 5.317    Mean   :0.07277   Mean   :0.07455  
 3rd Qu.: 8.00     3rd Qu.: 7.000    3rd Qu.:0.00000   3rd Qu.:0.00000  
 Max.   :13.00     Max.   :20.000    Max.   :1.00000   Max.   :1.00000  
                                                                        
  AcceptedCmp5      AcceptedCmp1      AcceptedCmp2    
 Min.   :0.00000   Min.   :0.00000   Min.   :0.00000  
 1st Qu.:0.00000   1st Qu.:0.00000   1st Qu.:0.00000  
 Median :0.00000   Median :0.00000   Median :0.00000  
 Mean   :0.07277   Mean   :0.06429   Mean   :0.01339  
 3rd Qu.:0.00000   3rd Qu.:0.00000   3rd Qu.:0.00000  
 Max.   :1.00000   Max.   :1.00000   Max.   :1.00000  
                                                      </code></pre>
</div>
</div>
<p>Calculons l’écart-type pour chaque variable :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stat.desc</span>(data)[<span class="dv">13</span>,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        Year_Birth Education Marital_Status   Income   Kidhome  Teenhome
std.dev   11.98407        NA             NA 25173.08 0.5383981 0.5445382
         Recency     Wine   Fruits     Meat     Fish  Sweets     Gold
std.dev 28.96245 336.5974 39.77343 225.7154 54.62898 41.2805 52.16744
        NumDealsPurchases NumWebPurchases NumCatalogPurchases NumStorePurchases
std.dev          1.932238        2.778714            2.923101          3.250958
        NumWebVisitsMonth AcceptedCmp3 AcceptedCmp4 AcceptedCmp5 AcceptedCmp1
std.dev          2.426645    0.2598131    0.2627283    0.2598131     0.245316
        AcceptedCmp2
std.dev    0.1149756</code></pre>
</div>
</div>
<p>Les ordres de grandeur différents indiquent la nécessité d’une réduction des données en divisant par l’écart-type.</p>
<p>Nous allons chercher si les données possèdent des valeurs manquantes :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(<span class="fu">which</span>(<span class="fu">sapply</span>(data, anyNA)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Income"</code></pre>
</div>
</div>
<p>La seule variable avec des valeurs manquantes est Income. Voyons de quels individus il s’agit ainsi que leur nombre :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>na_rows <span class="ot">&lt;-</span> <span class="fu">data.frame</span>()</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(data)){</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">anyNA</span>(data[i,])){</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>    na_rows <span class="ot">&lt;-</span> <span class="fu">rbind</span>(na_rows,data[i,])</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(na_rows)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Year_Birth  Education Marital_Status Income Kidhome Teenhome Recency Wine
1994        1983 Graduation        Married     NA       1        0      11    5
5255        1986 Graduation         Single     NA       1        0      19    5
7281        1959        PhD         Single     NA       0        0      80   81
7244        1951 Graduation         Single     NA       2        1      96   48
8557        1982 Graduation         Single     NA       1        0      57   11
10629       1973   2n Cycle        Married     NA       1        0      25   25
      Fruits Meat Fish Sweets Gold NumDealsPurchases NumWebPurchases
1994       5    6    0      2    1                 1               1
5255       1    3    3    263  362                 0              27
7281      11   50    3      2   39                 1               1
7244       5   48    6     10    7                 3               2
8557       3   22    2      2    6                 2               2
10629      3   43   17      4   17                 3               3
      NumCatalogPurchases NumStorePurchases NumWebVisitsMonth AcceptedCmp3
1994                    0                 2                 7            0
5255                    0                 0                 1            0
7281                    3                 4                 2            0
7244                    1                 4                 6            0
8557                    0                 3                 6            0
10629                   0                 3                 8            0
      AcceptedCmp4 AcceptedCmp5 AcceptedCmp1 AcceptedCmp2
1994             0            0            0            0
5255             0            0            0            0
7281             0            0            0            0
7244             0            0            0            0
8557             0            0            0            0
10629            0            0            0            0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(na_rows)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 24</code></pre>
</div>
</div>
<p>Nous remplacons les 24 valeurs manquantes par le revenu médian :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>Income <span class="ot">&lt;-</span> data<span class="sc">$</span>Income <span class="sc">%&gt;%</span> <span class="fu">replace_na</span>(<span class="fu">as.integer</span>(<span class="fu">median</span>(data<span class="sc">$</span>Income, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Pour notre classification, nous n’utiliserons que les douze variables portant sur le comportement d’achat des client. À savoire : les six variables sur le montant dépensé par catégorie, les cinq variables sur le nombre d’achats par canal de vente ainsi que la variable Recency.</p>
<p>Observons la distribution de ces différentes variables dans nos données :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(Wine<span class="sc">:</span>Gold, <span class="at">names_to =</span> <span class="st">"type"</span>, <span class="at">values_to =</span> <span class="st">"dépense"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">y =</span> dépense, <span class="at">x =</span> type)) <span class="sc">+</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">""</span>, <span class="at">y =</span> <span class="st">"Dépense (en $)"</span>, <span class="at">title =</span> <span class="st">"Dépense de chaque client par catégorie"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projetada_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(NumDealsPurchases<span class="sc">:</span>NumWebVisitsMonth, <span class="at">names_to =</span> <span class="st">"type"</span>, <span class="at">values_to =</span> <span class="st">"total"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">y =</span> total, <span class="at">x =</span> type)) <span class="sc">+</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">""</span>, <span class="at">y =</span> <span class="st">""</span>, <span class="at">title =</span> <span class="st">"Nombre d'achats ou de visites par canal et par client"</span>) <span class="sc">+</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projetada_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gghistogram</span>(data,<span class="at">x=</span><span class="st">"Recency"</span>,<span class="at">xlab=</span><span class="st">"Jours"</span>,<span class="at">ylab=</span><span class="st">"Nombre de clients"</span>,<span class="at">title =</span> <span class="st">"Histogramme du nombre de jours depuis le dernier achat"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using `bins = 30` by default. Pick better value with the argument
`bins`.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projetada_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Nous remarquons quelques valeurs extrêmes notamment pour les variables Wine, Meat, NumCatalogPurchases et NumWebPurchases. Mais ces valeurs restent probables, nous décidons donc de conserver l’ensemble des individus.</p>
<section id="traitement-des-valeurs-aberrantes" class="level3">
<h3 class="anchored" data-anchor-id="traitement-des-valeurs-aberrantes">1.1 Traitement des valeurs aberrantes</h3>
<p><strong>Income :</strong></p>
<p>On supprimera l’individu dont le revenu est de 666 666 $ car il s’agit clairement d’une valeur fantaisiste (cf les statistiques descriptives pour la variable Income).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Income <span class="sc">&gt;=</span> <span class="dv">10000</span> <span class="sc">&amp;</span> Income <span class="sc">&lt;</span> <span class="dv">666666</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Year_Birth :</strong></p>
<p>De même, la présence d’individus nés avant 1920 est improbable (l’individu né en 1893 notamment, cf les statistiques descriptives pour la variable Year_Birth)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Year_Birth <span class="sc">&gt;=</span> <span class="dv">1920</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Nous allons remplacer l’année de naissance du client par son âge en 2024 pour une interprétation plus aisée :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">Age =</span> <span class="dv">2024</span> <span class="sc">-</span> Year_Birth, <span class="at">.keep =</span> <span class="st">"unused"</span>, <span class="at">.before =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Marital_Status :</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data<span class="sc">$</span>Marital_Status)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Absurd    Alone Divorced  Married   Single Together    Widow     YOLO 
       2        3      228      853      469      573       77        2 </code></pre>
</div>
</div>
<p>Nous observons trois niveaux qui apparaissent seulement quelque fois pour le facteur de l’état matrimonial. Nous allons donc changer les niveaux Absurd, YOLO et Alone par single.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>Marital_Status <span class="ot">&lt;-</span><span class="fu">as.factor</span>(<span class="fu">case_match</span>(data<span class="sc">$</span>Marital_Status, <span class="st">"YOLO"</span> <span class="sc">~</span> <span class="st">"Single"</span>, <span class="st">"Absurd"</span> <span class="sc">~</span> <span class="st">"Single"</span>, <span class="st">"Alone"</span> <span class="sc">~</span> <span class="st">"Single"</span>, <span class="at">.default =</span> data<span class="sc">$</span>Marital_Status))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Education :</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data<span class="sc">$</span>Education)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  2n Cycle      Basic Graduation     Master        PhD 
       197         49       1113        367        481 </code></pre>
</div>
</div>
<p>Les différents niveaux du facteur Education sont assez bien représentés et ne seront donc pas regroupés à l’exception de Master et 2n Cycle qui correspondent à la même chose.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>Education <span class="ot">&lt;-</span><span class="fu">as.factor</span>(<span class="fu">case_match</span>(data<span class="sc">$</span>Education, <span class="st">"2n Cycle"</span> <span class="sc">~</span> <span class="st">"Master"</span>, <span class="at">.default =</span> data<span class="sc">$</span>Education))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>AcceptedCmp :</strong></p>
<p>Par défaut, les variables d’acceptation des différentes campagne marketing sont interprétées par R comme des variables quantitatives. Nous les transformons donc en variables qualitatives.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>AcceptedCmp1 <span class="ot">&lt;-</span>  <span class="fu">factor</span>(data<span class="sc">$</span>AcceptedCmp1, <span class="at">levels=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), <span class="at">labels=</span><span class="fu">c</span>(<span class="st">"No"</span>, <span class="st">"Yes"</span>))</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>AcceptedCmp2 <span class="ot">&lt;-</span>  <span class="fu">factor</span>(data<span class="sc">$</span>AcceptedCmp2, <span class="at">levels=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), <span class="at">labels=</span><span class="fu">c</span>(<span class="st">"No"</span>, <span class="st">"Yes"</span>))</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>AcceptedCmp3 <span class="ot">&lt;-</span>  <span class="fu">factor</span>(data<span class="sc">$</span>AcceptedCmp3, <span class="at">levels=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), <span class="at">labels=</span><span class="fu">c</span>(<span class="st">"No"</span>, <span class="st">"Yes"</span>))</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>AcceptedCmp4 <span class="ot">&lt;-</span>  <span class="fu">factor</span>(data<span class="sc">$</span>AcceptedCmp4, <span class="at">levels=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), <span class="at">labels=</span><span class="fu">c</span>(<span class="st">"No"</span>, <span class="st">"Yes"</span>))</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>AcceptedCmp5 <span class="ot">&lt;-</span>  <span class="fu">factor</span>(data<span class="sc">$</span>AcceptedCmp5, <span class="at">levels=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), <span class="at">labels=</span><span class="fu">c</span>(<span class="st">"No"</span>, <span class="st">"Yes"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data[,<span class="dv">19</span><span class="sc">:</span><span class="dv">23</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> AcceptedCmp3 AcceptedCmp4 AcceptedCmp5 AcceptedCmp1 AcceptedCmp2
 No :2046     No :2040     No :2045     No :2063     No :2177    
 Yes: 161     Yes: 167     Yes: 162     Yes: 144     Yes:  30    </code></pre>
</div>
</div>
</section>
<section id="création-de-nouvelles-variables" class="level3">
<h3 class="anchored" data-anchor-id="création-de-nouvelles-variables">1.2 Création de nouvelles variables</h3>
<p>Nous allons créer quatre nouvelles variables :</p>
<ul>
<li><p>Montant : somme des dépenses dans les six catégories de produits</p></li>
<li><p>Fréquence : nombre d’achats total</p></li>
<li><p>Moyenne : panier moyen de chaque client</p></li>
<li><p>Score : pourcentage du salaire dépensé dans le magasin</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Montant =</span> <span class="fu">rowSums</span>(<span class="fu">across</span>(<span class="fu">c</span>(Gold, Fish, Meat, Sweets, Fruits,Wine)))) <span class="sc">%&gt;%</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(Fréquence <span class="ot">=</span> <span class="fu">rowSums</span>(<span class="fu">across</span>(<span class="fu">c</span>(NumCatalogPurchases, NumWebPurchases, NumStorePurchases)))) <span class="sc">%&gt;%</span> </span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Fréquence <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Moyenne =</span> Montant<span class="sc">/</span>Fréquence) <span class="sc">%&gt;%</span> </span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>   <span class="fu">filter</span>(Income <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Score =</span> <span class="dv">100</span><span class="sc">*</span>Montant<span class="sc">/</span>Income)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="classification" class="level2">
<h2 class="anchored" data-anchor-id="classification">2. Classification</h2>
<p>Nous rappelons les variables qui seront utilisées pour la classification : Recency, Wine, Fruits, Meat, Fish, Sweets, Gold, NumDealsPurchases, NumWebPurchases, NumCatalogPurchases, NumStorePurchases, NumWebVisitsMonths, Moyenne et Score. Les autres variables, qui correspondent aux informations personnelles et aux offres promotionnelles seront illustratives. Puisque l’on fera une ACP, les variables Montant et Fréquence seront aussi illustratives car ce sont des combinaisons linéaires d’autres variables actives.</p>
<section id="réduction-de-dimension-par-acp" class="level3">
<h3 class="anchored" data-anchor-id="réduction-de-dimension-par-acp">2.1 Réduction de dimension par ACP</h3>
<p>Les 14 variables utilisées pour la classification sont toutes quantitatives, on peut donc réaliser une ACP avant de procéder à une classification ascendante hiérarchique grâce à la fonction HCPC. Les autres variables sont supplémentaires et permettront de décrire les clusters.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>res.pca <span class="ot">&lt;-</span> <span class="fu">PCA</span>(data, <span class="at">scale.unit =</span> T, <span class="at">quali.sup =</span> <span class="fu">c</span>(<span class="dv">2</span><span class="sc">:</span><span class="dv">3</span>,<span class="dv">19</span><span class="sc">:</span><span class="dv">23</span>), <span class="at">quanti.sup =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">4</span><span class="sc">:</span><span class="dv">6</span>,<span class="dv">24</span>,<span class="dv">25</span>), <span class="at">ncp =</span> <span class="cn">Inf</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projetada_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projetada_files/figure-html/unnamed-chunk-24-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_eig</span>(res.pca)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projetada_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>res.pca<span class="sc">$</span>eig</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        eigenvalue percentage of variance cumulative percentage of variance
comp 1  6.35410601              45.386472                          45.38647
comp 2  1.65401956              11.814425                          57.20090
comp 3  1.00454513               7.175322                          64.37622
comp 4  0.92044033               6.574574                          70.95079
comp 5  0.71847473               5.131962                          76.08276
comp 6  0.62244372               4.446027                          80.52878
comp 7  0.61574193               4.398157                          84.92694
comp 8  0.46482918               3.320208                          88.24715
comp 9  0.44402348               3.171596                          91.41874
comp 10 0.39608919               2.829208                          94.24795
comp 11 0.32855606               2.346829                          96.59478
comp 12 0.26053324               1.860952                          98.45573
comp 13 0.18243279               1.303091                          99.75882
comp 14 0.03376465               0.241176                         100.00000</code></pre>
</div>
</div>
<p><strong>Combien d’axes retenir ?</strong></p>
<p>Le critère du coude nous dit de retenir les 3 premières composantes principales. Celles ci expliquent 64% de la variance des données. Nous pourrions aussi fixer un seuil de variance à expliquer, à 80% par exemple, et donc décider de retenir les 6 premières composantes principales. Une autre solution serait de retenir toutes les composantes principales.</p>
<p>Nous allons envisager les trois solutions et les comparer. Nous predrons comme nombre de cluster le choix par défaut de la fonction HCPC qui sera 3 dans les 3 cas :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>res.pca<span class="fl">.3</span> <span class="ot">&lt;-</span> <span class="fu">PCA</span>(data, <span class="at">scale.unit =</span> T, <span class="at">quali.sup =</span> <span class="fu">c</span>(<span class="dv">2</span><span class="sc">:</span><span class="dv">3</span>,<span class="dv">19</span><span class="sc">:</span><span class="dv">23</span>), <span class="at">quanti.sup =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">4</span><span class="sc">:</span><span class="dv">6</span>,<span class="dv">24</span>,<span class="dv">25</span>), <span class="at">ncp =</span> <span class="dv">3</span>, <span class="at">graph =</span> F)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>res.pca<span class="fl">.6</span> <span class="ot">&lt;-</span> <span class="fu">PCA</span>(data, <span class="at">scale.unit =</span> T, <span class="at">quali.sup =</span> <span class="fu">c</span>(<span class="dv">2</span><span class="sc">:</span><span class="dv">3</span>,<span class="dv">19</span><span class="sc">:</span><span class="dv">23</span>), <span class="at">quanti.sup =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">4</span><span class="sc">:</span><span class="dv">6</span>,<span class="dv">24</span>,<span class="dv">25</span>), <span class="at">ncp =</span> <span class="dv">6</span>, <span class="at">graph =</span> F)</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>res.hcpc <span class="ot">&lt;-</span> <span class="fu">HCPC</span>(res.pca, <span class="at">nb.clust =</span> <span class="sc">-</span><span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>res.hcpc<span class="fl">.3</span> <span class="ot">&lt;-</span> <span class="fu">HCPC</span>(res.pca<span class="fl">.3</span>, <span class="at">nb.clust =</span> <span class="sc">-</span><span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>res.hcpc<span class="fl">.6</span> <span class="ot">&lt;-</span> <span class="fu">HCPC</span>(res.pca<span class="fl">.6</span>, <span class="at">nb.clust =</span> <span class="sc">-</span><span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Observons si les classes sont stables :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>parti.Inf <span class="ot">&lt;-</span> res.hcpc<span class="sc">$</span>data.clust<span class="sc">$</span>clust</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="co"># avec 3 coordonn?es factorielles </span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>parti<span class="fl">.3</span> <span class="ot">&lt;-</span> res.hcpc<span class="fl">.3</span><span class="sc">$</span>data.clust<span class="sc">$</span>clust</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a><span class="co"># avec 6 coordonn?es factorielles </span></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>parti<span class="fl">.6</span> <span class="ot">&lt;-</span> res.hcpc<span class="fl">.6</span><span class="sc">$</span>data.clust<span class="sc">$</span>clust</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Le tableau crois?</span></span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(parti.Inf, parti<span class="fl">.6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         parti.6
parti.Inf    1    2    3
        1 1037    4    0
        2   14  539   42
        3    0    2  567</code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(parti.Inf, parti<span class="fl">.3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         parti.3
parti.Inf    1    2    3
        1 1022   19    0
        2   19  530   46
        3    0    2  567</code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(parti<span class="fl">.3</span>, parti<span class="fl">.6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       parti.6
parti.3    1    2    3
      1 1035    6    0
      2   16  530    5
      3    0    9  604</code></pre>
</div>
</div>
<p>La différence la plus notable est au sein des classes 2 et 3 pour la classification avec 14 composantes principales et 3 composantes principales respectivement. Mais globalement les classes sont assez stables.</p>
<p>Pour choisir combien de composantes retenir nous utiliserons le critère de l’inertie intra. Comme l’inertie totale varie en fonction du nombre d’axes retenus puisque nous avons éliminé de l’information, nous allons diviser l’inertie totale par l’inertie intra de la classification à trois classes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Avec tous les axes</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>(W <span class="ot">&lt;-</span> res.hcpc<span class="sc">$</span>call<span class="sc">$</span>t<span class="sc">$</span>within)</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>(Tot <span class="ot">&lt;-</span> W[<span class="dv">1</span>]) ; (W[<span class="dv">3</span>]) <span class="co"># 14 6.565559</span></span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>(W[<span class="dv">3</span>]<span class="sc">/</span>W[<span class="dv">1</span>]) <span class="co"># 0.5468982</span></span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Avec 3 axes</span></span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a>(W <span class="ot">&lt;-</span> res.hcpc<span class="fl">.3</span><span class="sc">$</span>call<span class="sc">$</span>t<span class="sc">$</span>within)</span>
<span id="cb50-9"><a href="#cb50-9" aria-hidden="true" tabindex="-1"></a>(Tot <span class="ot">&lt;-</span> W[<span class="dv">1</span>]) ; (W[<span class="dv">3</span>]) <span class="co"># 9.45147 3.083783</span></span>
<span id="cb50-10"><a href="#cb50-10" aria-hidden="true" tabindex="-1"></a>(W[<span class="dv">3</span>]<span class="sc">/</span>W[<span class="dv">1</span>]) <span class="co"># 0.3262755</span></span>
<span id="cb50-11"><a href="#cb50-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-12"><a href="#cb50-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Avec 6 axes</span></span>
<span id="cb50-13"><a href="#cb50-13" aria-hidden="true" tabindex="-1"></a>(W <span class="ot">&lt;-</span> res.hcpc<span class="fl">.6</span><span class="sc">$</span>call<span class="sc">$</span>t<span class="sc">$</span>within)</span>
<span id="cb50-14"><a href="#cb50-14" aria-hidden="true" tabindex="-1"></a>(Tot <span class="ot">&lt;-</span> W[<span class="dv">1</span>]) ; (W[<span class="dv">3</span>]) <span class="co"># 11.58942 5.225293</span></span>
<span id="cb50-15"><a href="#cb50-15" aria-hidden="true" tabindex="-1"></a>(W[<span class="dv">3</span>]<span class="sc">/</span>W[<span class="dv">1</span>]) <span class="co"># 0.4508675</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Avec 3 axes, l’inertie intra représente 32.6% de l’inertie totale contre 45% et 54% pour la classification avec 6 axes et 14 axes respectivement. Les trois classes sont le plus homogènes (ou mieux séparées) pour une classification faite à partir des 3 axes.</p>
</section>
<section id="choix-du-nombre-de-cluster" class="level3">
<h3 class="anchored" data-anchor-id="choix-du-nombre-de-cluster">2.3 Choix du nombre de cluster</h3>
<p>Le critère par défaut de la fonction HCPC propose de choisir une partition en 3 classes mais il existe d’autres critères.</p>
<p><strong>Statistique du Gap</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_nbclust</span>(res.pca<span class="fl">.3</span><span class="sc">$</span>ind<span class="sc">$</span>coord,hcut,<span class="at">method =</span> <span class="st">"gap_stat"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projetada_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Somme des carrés intra</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_nbclust</span>(res.pca<span class="fl">.3</span><span class="sc">$</span>ind<span class="sc">$</span>coord,hcut,<span class="at">method =</span> <span class="st">"wss"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projetada_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Il existe de nombreux critères pour déterminer le nombre de classes possibles. La méthode du Gap est basée sur la maximisation de l’écart entre l’inertie intra classe observée et l’inertie intra de données aléatoires. Nous trouvons une valeur de trois classes grâce à cette méthode. Une autre méthode consiste à tracer la somme des carrés intra en fonction du nombre de classes et de trouver un coude sur la courbe qui indique que l’augmentation du nombre de classe ne conduirait pas à une amélioration significative de la classification. Sur la courbe ci-dessus, nous observons un coude après trois classes. Encore une fois ce critère nous conduit à choisir une classification en trois classes.</p>
<p>Le package NbClust contient une fonction qui calcule 23 indices pour déterminer le meilleur nombre de cluster. :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>nb <span class="ot">&lt;-</span> <span class="fu">NbClust</span>(res.pca<span class="fl">.3</span><span class="sc">$</span>ind<span class="sc">$</span>coord, <span class="at">method=</span><span class="st">"ward.D2"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projetada_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>*** : The Hubert index is a graphical method of determining the number of clusters.
                In the plot of Hubert index, we seek a significant knee that corresponds to a 
                significant increase of the value of the measure i.e the significant peak in Hubert
                index second differences plot. 
 </code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projetada_files/figure-html/unnamed-chunk-32-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>*** : The D index is a graphical method of determining the number of clusters. 
                In the plot of D index, we seek a significant knee (the significant peak in Dindex
                second differences plot) that corresponds to a significant increase of the value of
                the measure. 
 
******************************************************************* 
* Among all indices:                                                
* 4 proposed 2 as the best number of clusters 
* 16 proposed 3 as the best number of clusters 
* 1 proposed 5 as the best number of clusters 
* 1 proposed 14 as the best number of clusters 
* 1 proposed 15 as the best number of clusters 

                   ***** Conclusion *****                            
 
* According to the majority rule, the best number of clusters is  3 
 
 
******************************************************************* </code></pre>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co">#******************************************************************* </span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="co">#* Among all indices:                                                </span></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a><span class="co">#* 4 proposed 2 as the best number of clusters </span></span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a><span class="co">#* 10 proposed 3 as the best number of clusters </span></span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a><span class="co">#* 5 proposed 4 as the best number of clusters </span></span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a><span class="co">#* 1 proposed 5 as the best number of clusters </span></span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a><span class="co">#* 2 proposed 6 as the best number of clusters </span></span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a><span class="co">#* 1 proposed 15 as the best number of clusters </span></span>
<span id="cb56-9"><a href="#cb56-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-10"><a href="#cb56-10" aria-hidden="true" tabindex="-1"></a><span class="co">#                   ***** Conclusion *****                            </span></span>
<span id="cb56-11"><a href="#cb56-11" aria-hidden="true" tabindex="-1"></a> <span class="co">#</span></span>
<span id="cb56-12"><a href="#cb56-12" aria-hidden="true" tabindex="-1"></a><span class="co">#* According to the majority rule, the best number of clusters is  3 </span></span>
<span id="cb56-13"><a href="#cb56-13" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb56-14"><a href="#cb56-14" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb56-15"><a href="#cb56-15" aria-hidden="true" tabindex="-1"></a><span class="co">#*******************************************************************</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Dix de ces indices ont proposé de choisir 3 cluster.</p>
<p>Nous retiendrons donc une classification à trois classes.</p>
</section>
<section id="classification-ascendante-hiérarchique-avec-trois-classes" class="level3">
<h3 class="anchored" data-anchor-id="classification-ascendante-hiérarchique-avec-trois-classes">2.3 Classification ascendante hiérarchique avec trois classes</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>res.hcpc <span class="ot">&lt;-</span> <span class="fu">HCPC</span>(res.pca<span class="fl">.3</span>, <span class="at">nb.clust =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projetada_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projetada_files/figure-html/unnamed-chunk-33-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projetada_files/figure-html/unnamed-chunk-33-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="description-des-classes-obtenues" class="level3">
<h3 class="anchored" data-anchor-id="description-des-classes-obtenues">2.4 Description des classes obtenues</h3>
<section id="parangons-de-chaque-classes" class="level4">
<h4 class="anchored" data-anchor-id="parangons-de-chaque-classes">Parangons de chaque classes</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>res.hcpc<span class="sc">$</span>desc.ind<span class="sc">$</span>para</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Cluster: 1
       229       1102       1394        939       1605 
0.03911407 0.11756131 0.11756131 0.16400619 0.19481659 
------------------------------------------------------------ 
Cluster: 2
       50       720       248      1725      1666 
0.3647193 0.3647193 0.3748459 0.3748459 0.4338355 
------------------------------------------------------------ 
Cluster: 3
      197       952       616       723       305 
0.1730392 0.2827161 0.3068261 0.3138006 0.3139772 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">catdes</span>(res.hcpc<span class="sc">$</span>data.clust,<span class="dv">28</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Link between the cluster variable and the categorical variables (chi-square test)
=================================================================================
                  p.value df
AcceptedCmp5 1.548883e-68  2
AcceptedCmp1 4.083845e-52  2
AcceptedCmp4 5.474690e-24  2
Education    1.883733e-13  6
AcceptedCmp2 4.368278e-05  2

Description of each cluster by the categories
=============================================
$`1`
                                 Cla/Mod     Mod/Cla    Global      p.value
AcceptedCmp5=AcceptedCmp5_No  50.9055311 99.90393852 92.653061 6.440282e-46
AcceptedCmp1=AcceptedCmp1_No  50.4609413 99.90393852 93.469388 1.916713e-40
AcceptedCmp4=AcceptedCmp4_No  50.2944063 98.46301633 92.426304 1.699266e-27
Education=Basic               95.9183673  4.51488953  2.222222 1.002249e-13
AcceptedCmp2=AcceptedCmp2_No  47.7701149 99.80787704 98.639456 1.676150e-06
Marital_Status=Widow          35.0649351  2.59365994  3.492063 2.968691e-02
Education=PhD                 41.8750000 19.30835735 21.768707 8.072523e-03
AcceptedCmp2=AcceptedCmp2_Yes  6.6666667  0.19212296  1.360544 1.676150e-06
AcceptedCmp4=AcceptedCmp4_Yes  9.5808383  1.53698367  7.573696 1.699266e-27
AcceptedCmp1=AcceptedCmp1_Yes  0.6944444  0.09606148  6.530612 1.916713e-40
AcceptedCmp5=AcceptedCmp5_Yes  0.6172840  0.09606148  7.346939 6.440282e-46
                                  v.test
AcceptedCmp5=AcceptedCmp5_No   14.224675
AcceptedCmp1=AcceptedCmp1_No   13.314099
AcceptedCmp4=AcceptedCmp4_No   10.864621
Education=Basic                 7.440605
AcceptedCmp2=AcceptedCmp2_No    4.788999
Marital_Status=Widow           -2.174243
Education=PhD                  -2.649021
AcceptedCmp2=AcceptedCmp2_Yes  -4.788999
AcceptedCmp4=AcceptedCmp4_Yes -10.864621
AcceptedCmp1=AcceptedCmp1_Yes -13.314099
AcceptedCmp5=AcceptedCmp5_Yes -14.224675

$`2`
                                Cla/Mod    Mod/Cla    Global      p.value
AcceptedCmp4=AcceptedCmp4_Yes 48.502994 14.7005445  7.573696 8.382972e-12
Education=PhD                 33.125000 28.8566243 21.768707 5.324616e-06
AcceptedCmp5=AcceptedCmp5_No  25.991189 96.3702359 92.653061 4.191833e-05
AcceptedCmp1=AcceptedCmp1_No  25.521591 95.4627949 93.469388 2.508040e-02
AcceptedCmp2=AcceptedCmp2_Yes 43.333333  2.3593466  1.360544 2.852020e-02
Marital_Status=Single         21.218487 18.3303085 21.587302 3.046194e-02
AcceptedCmp2=AcceptedCmp2_No  24.735632 97.6406534 98.639456 2.852020e-02
AcceptedCmp1=AcceptedCmp1_Yes 17.361111  4.5372051  6.530612 2.508040e-02
Education=Graduation          22.841727 46.0980036 50.430839 1.895090e-02
Education=Basic                4.081633  0.3629764  2.222222 1.102913e-04
AcceptedCmp5=AcceptedCmp5_Yes 12.345679  3.6297641  7.346939 4.191833e-05
AcceptedCmp4=AcceptedCmp4_No  23.061825 85.2994555 92.426304 8.382972e-12
                                 v.test
AcceptedCmp4=AcceptedCmp4_Yes  6.831844
Education=PhD                  4.551574
AcceptedCmp5=AcceptedCmp5_No   4.096644
AcceptedCmp1=AcceptedCmp1_No   2.240162
AcceptedCmp2=AcceptedCmp2_Yes  2.190056
Marital_Status=Single         -2.164031
AcceptedCmp2=AcceptedCmp2_No  -2.190056
AcceptedCmp1=AcceptedCmp1_Yes -2.240162
Education=Graduation          -2.346495
Education=Basic               -3.866759
AcceptedCmp5=AcceptedCmp5_Yes -4.096644
AcceptedCmp4=AcceptedCmp4_No  -6.831844

$`3`
                               Cla/Mod   Mod/Cla    Global      p.value
AcceptedCmp5=AcceptedCmp5_Yes 87.03704 23.001631  7.346939 5.757236e-61
AcceptedCmp1=AcceptedCmp1_Yes 81.94444 19.249592  6.530612 9.888636e-45
AcceptedCmp4=AcceptedCmp4_Yes 41.91617 11.419250  7.573696 4.586950e-05
Education=Graduation          31.02518 56.280587 50.430839 6.528050e-04
AcceptedCmp2=AcceptedCmp2_Yes 50.00000  2.446982  1.360544 1.035126e-02
AcceptedCmp2=AcceptedCmp2_No  27.49425 97.553018 98.639456 1.035126e-02
AcceptedCmp4=AcceptedCmp4_No  26.64377 88.580750 92.426304 4.586950e-05
Education=Basic                0.00000  0.000000  2.222222 9.493165e-08
AcceptedCmp1=AcceptedCmp1_No  24.01747 80.750408 93.469388 9.888636e-45
AcceptedCmp5=AcceptedCmp5_No  23.10328 76.998369 92.653061 5.757236e-61
                                  v.test
AcceptedCmp5=AcceptedCmp5_Yes  16.472770
AcceptedCmp1=AcceptedCmp1_Yes  14.032304
AcceptedCmp4=AcceptedCmp4_Yes   4.075734
Education=Graduation            3.408670
AcceptedCmp2=AcceptedCmp2_Yes   2.563869
AcceptedCmp2=AcceptedCmp2_No   -2.563869
AcceptedCmp4=AcceptedCmp4_No   -4.075734
Education=Basic                -5.336168
AcceptedCmp1=AcceptedCmp1_No  -14.032304
AcceptedCmp5=AcceptedCmp5_No  -16.472770


Link between the cluster variable and the quantitative variables
================================================================
                          Eta2       P-value
Income              0.62426614  0.000000e+00
Wine                0.55137522  0.000000e+00
Meat                0.62356001  0.000000e+00
Fish                0.50190733  0.000000e+00
NumWebPurchases     0.49820556  0.000000e+00
NumCatalogPurchases 0.60011590  0.000000e+00
NumStorePurchases   0.53009758  0.000000e+00
Montant             0.77987604  0.000000e+00
Fréquence           0.75499019  0.000000e+00
Score               0.75606997  0.000000e+00
Fruits              0.44824331 4.614417e-285
Sweets              0.43425930 4.283329e-273
NumWebVisitsMonth   0.41759134 3.279728e-259
Kidhome             0.32081921 1.037336e-185
Gold                0.30922655 1.283918e-177
Moyenne             0.30341391 1.303929e-173
NumDealsPurchases   0.30058359 1.132747e-171
Teenhome            0.16910904  2.618069e-89
Age                 0.03036303  1.805890e-15

Description of each cluster by quantitative variables
=====================================================
$`1`
                        v.test Mean in category Overall mean sd in category
Kidhome              24.953813     7.454371e-01 4.426304e-01   5.126084e-01
NumWebVisitsMonth    17.920632     6.186359e+00 5.262585e+00   1.760340e+00
Age                  -7.567796     5.319693e+01 5.518730e+01   1.104356e+01
NumDealsPurchases    -8.717417     1.943324e+00 2.308390e+00   1.113905e+00
Moyenne             -22.895029     1.461464e+01 3.825134e+01   7.881729e+00
Sweets              -23.677736     5.261287e+00 2.738866e+01   7.717448e+00
Fruits              -23.681165     5.261287e+00 2.654921e+01   8.787432e+00
Fish                -24.758537     7.389049e+00 3.799320e+01   1.166106e+01
Gold                -25.381701     1.459270e+01 4.401950e+01   1.540280e+01
Meat                -28.550282     2.432757e+01 1.683986e+02   2.534483e+01
NumWebPurchases     -32.107998     2.143132e+00 4.104762e+00   1.247350e+00
NumCatalogPurchases -32.140863     5.955812e-01 2.681633e+00   7.869857e-01
NumStorePurchases   -33.848588     3.391931e+00 5.854875e+00   1.257482e+00
Income              -33.888436     3.666435e+04 5.245278e+04   1.360258e+04
Wine                -34.167583     4.875600e+01 3.081859e+02   6.328902e+01
Montant             -37.370040     1.055879e+02 6.125351e+02   9.802645e+01
Score               -38.995181     2.770816e-01 9.554742e-01   2.003084e-01
Fréquence           -40.364707     6.130644e+00 1.264127e+01   2.627029e+00
                      Overall sd       p.value
Kidhome             5.387450e-01 1.941289e-137
NumWebVisitsMonth   2.288586e+00  8.139869e-72
Age                 1.167670e+01  3.796090e-14
NumDealsPurchases   1.859253e+00  2.846196e-18
Moyenne             4.583531e+01 5.207373e-116
Sweets              4.149009e+01 6.115648e-124
Fruits              3.991028e+01 5.637965e-124
Fish                5.487948e+01 2.508843e-135
Gold                5.147271e+01 4.016206e-142
Meat                2.240377e+02 2.786427e-179
NumWebPurchases     2.712430e+00 3.409666e-226
NumCatalogPurchases 2.881523e+00 1.185077e-226
NumStorePurchases   3.230492e+00 3.807063e-251
Income              2.068437e+04 9.861603e-252
Wine                3.371014e+02 7.330064e-256
Montant             6.022737e+02 1.198596e-305
Score               7.723691e-01  0.000000e+00
Fréquence           7.161032e+00  0.000000e+00

$`2`
                       v.test Mean in category Overall mean sd in category
NumDealsPurchases   25.050073     4.027223e+00 2.308390e+00   2.368345e+00
NumWebPurchases     24.390185     6.546279e+00 4.104762e+00   2.390457e+00
Fréquence           17.097268     1.715971e+01 1.264127e+01   4.226772e+00
Teenhome            17.022323     8.511797e-01 5.092971e-01   4.890762e-01
NumStorePurchases   14.491519     7.582577e+00 5.854875e+00   2.667269e+00
Wine                12.856224     4.681270e+02 3.081859e+02   2.895756e+02
Score               11.168907     1.273837e+00 9.554742e-01   4.779809e-01
NumWebVisitsMonth   10.729271     6.168784e+00 5.262585e+00   1.713247e+00
Gold                 8.736421     6.061525e+01 4.401950e+01   5.167634e+01
Age                  6.733413     5.808893e+01 5.518730e+01   1.044549e+01
Income               5.860437     5.692640e+04 5.245278e+04   1.182035e+04
Montant              5.354523     7.315499e+02 6.125351e+02   3.324070e+02
NumCatalogPurchases  3.283910     3.030853e+00 2.681633e+00   1.918709e+00
Moyenne              2.423123     4.235018e+01 3.825134e+01   1.795181e+01
Sweets              -3.759862     2.163158e+01 2.738866e+01   2.873087e+01
Meat                -4.230631     1.334192e+02 1.683986e+02   9.023619e+01
Fruits              -4.391045     2.008167e+01 2.654921e+01   2.409032e+01
Fish                -5.094505     2.767514e+01 3.799320e+01   3.268623e+01
Kidhome             -5.923145     3.248639e-01 4.426304e-01   5.055937e-01
                      Overall sd       p.value
NumDealsPurchases   1.859253e+00 1.742632e-138
NumWebPurchases     2.712430e+00 2.173735e-131
Fréquence           7.161032e+00  1.555269e-65
Teenhome            5.442169e-01  5.610042e-65
NumStorePurchases   3.230492e+00  1.370779e-47
Wine                3.371014e+02  7.935984e-38
Score               7.723691e-01  5.788872e-29
NumWebVisitsMonth   2.288586e+00  7.417905e-27
Gold                5.147271e+01  2.406118e-18
Age                 1.167670e+01  1.657289e-11
Income              2.068437e+04  4.616498e-09
Montant             6.022737e+02  8.578241e-08
NumCatalogPurchases 2.881523e+00  1.023777e-03
Moyenne             4.583531e+01  1.538770e-02
Sweets              4.149009e+01  1.700068e-04
Meat                2.240377e+02  2.330365e-05
Fruits              3.991028e+01  1.128070e-05
Fish                5.487948e+01  3.496545e-07
Kidhome             5.387450e-01  3.158415e-09

$`3`
                       v.test Mean in category Overall mean sd in category
Montant              36.46681     1.366458e+03 6.125351e+02   4.142164e+02
Meat                 35.90177     4.445024e+02 1.683986e+02   2.440394e+02
Score                32.65887     1.821362e+00 9.554742e-01   4.999393e-01
NumCatalogPurchases  32.64094     5.910277e+00 2.681633e+00   2.753632e+00
Fish                 32.51147     9.923980e+01 3.799320e+01   6.484462e+01
Income               32.09838     7.524365e+04 5.245278e+04   1.176598e+04
Fruits               30.63116     6.851387e+01 2.654921e+01   5.008510e+01
Sweets               30.01738     7.014029e+01 2.738866e+01   5.157516e+01
Fréquence            28.45596     1.963622e+01 1.264127e+01   4.173222e+00
Wine                 25.64894     6.049869e+02 3.081859e+02   3.181276e+02
NumStorePurchases    23.71319     8.484502e+00 5.854875e+00   2.925698e+00
Moyenne              23.17019     7.470701e+01 3.825134e+01   6.977765e+01
Gold                 19.84011     7.907504e+01 4.401950e+01   6.148145e+01
NumWebPurchases      12.20792     5.241436e+00 4.104762e+00   2.345475e+00
NumDealsPurchases   -14.49377     1.383361e+00 2.308390e+00   1.244177e+00
Teenhome            -14.60044     2.365416e-01 5.092971e-01   4.400457e-01
Kidhome             -22.08197     3.425775e-02 4.426304e-01   1.818905e-01
NumWebVisitsMonth   -30.33727     2.879282e+00 5.262585e+00   1.752680e+00
                      Overall sd       p.value
Montant             6.022737e+02 3.725729e-291
Meat                2.240377e+02 2.866677e-282
Score               7.723691e-01 5.996473e-234
NumCatalogPurchases 2.881523e+00 1.077566e-233
Fish                5.487948e+01 7.342779e-232
Income              2.068437e+04 4.644767e-226
Fruits              3.991028e+01 4.710531e-206
Sweets              4.149009e+01 5.821558e-198
Fréquence           7.161032e+00 4.112390e-178
Wine                3.371014e+02 4.345060e-145
NumStorePurchases   3.230492e+00 2.636144e-124
Moyenne             4.583531e+01 9.100668e-119
Gold                5.147271e+01  1.341556e-87
NumWebPurchases     2.712430e+00  2.820056e-34
NumDealsPurchases   1.859253e+00  1.326480e-47
Teenhome            5.442169e-01  2.790455e-48
Kidhome             5.387450e-01 4.710503e-108
NumWebVisitsMonth   2.288586e+00 3.698415e-202</code></pre>
</div>
</div>
</section>
<section id="lien-entre-les-cluster-et-les-variable-qualitatives" class="level4">
<h4 class="anchored" data-anchor-id="lien-entre-les-cluster-et-les-variable-qualitatives">Lien entre les cluster et les variable qualitatives</h4>
<p>La variable qualitative la plus liée à la variable “cluster” est AcceptedCmp5.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(res.hcpc<span class="sc">$</span>data.clust<span class="sc">$</span>clust,res.hcpc<span class="sc">$</span>data.clust<span class="sc">$</span>AcceptedCmp5)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   
    AcceptedCmp5_No AcceptedCmp5_Yes
  1            1040                1
  2             531               20
  3             472              141</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>tib <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">clust =</span> res.hcpc<span class="sc">$</span>data.clust<span class="sc">$</span>clust,</span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">AcceptedCmp1 =</span> res.hcpc<span class="sc">$</span>data.clust<span class="sc">$</span>AcceptedCmp5</span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a>tib <span class="sc">%&gt;%</span> </span>
<span id="cb64-6"><a href="#cb64-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>clust,</span>
<span id="cb64-7"><a href="#cb64-7" aria-hidden="true" tabindex="-1"></a>             <span class="at">fill=</span><span class="fu">factor</span>(AcceptedCmp1)))<span class="sc">+</span></span>
<span id="cb64-8"><a href="#cb64-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"dodge"</span>)<span class="sc">+</span></span>
<span id="cb64-9"><a href="#cb64-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Cluster"</span>,</span>
<span id="cb64-10"><a href="#cb64-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">y=</span><span class="st">"AcceptedCmp1"</span>,</span>
<span id="cb64-11"><a href="#cb64-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Bar Plot of Label Data"</span>,</span>
<span id="cb64-12"><a href="#cb64-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill=</span><span class="st">"Binary Variable"</span>)<span class="sc">+</span></span>
<span id="cb64-13"><a href="#cb64-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"darkred"</span>,</span>
<span id="cb64-14"><a href="#cb64-14" aria-hidden="true" tabindex="-1"></a>                               <span class="st">"darkblue"</span>))<span class="sc">+</span></span>
<span id="cb64-15"><a href="#cb64-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projetada_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Nous remarquons qu’aucun client du cluster 1 n’a accepté une offre durant la cinquième campagne promotionnelle. Celle ci est davantage accepté par les clients du cluster 3 même si le pourcentage d’acceptation reste faible. L’analyse est la même pour la première campagne.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(res.hcpc<span class="sc">$</span>data.clust<span class="sc">$</span>clust,res.hcpc<span class="sc">$</span>data.clust<span class="sc">$</span>AcceptedCmp1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   
    AcceptedCmp1_No AcceptedCmp1_Yes
  1            1040                1
  2             526               25
  3             495              118</code></pre>
</div>
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(res.hcpc<span class="sc">$</span>data.clust<span class="sc">$</span>clust,res.hcpc<span class="sc">$</span>data.clust<span class="sc">$</span>AcceptedCmp2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   
    AcceptedCmp2_No AcceptedCmp2_Yes
  1            1039                2
  2             538               13
  3             598               15</code></pre>
</div>
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(res.hcpc<span class="sc">$</span>data.clust<span class="sc">$</span>clust,res.hcpc<span class="sc">$</span>data.clust<span class="sc">$</span>AcceptedCmp3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   
    AcceptedCmp3_No AcceptedCmp3_Yes
  1             974               67
  2             504               47
  3             566               47</code></pre>
</div>
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(res.hcpc<span class="sc">$</span>data.clust<span class="sc">$</span>clust,res.hcpc<span class="sc">$</span>data.clust<span class="sc">$</span>AcceptedCmp4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   
    AcceptedCmp4_No AcceptedCmp4_Yes
  1            1025               16
  2             470               81
  3             543               70</code></pre>
</div>
</div>
<p>Les offres de la deuxième campagne semblent être rejetées par tout le monde. Cependant, les offres de la troisième campagne ont eu davantage de succès auprès des clients du premier cluster.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(res.hcpc<span class="sc">$</span>data.clust<span class="sc">$</span>clust,res.hcpc<span class="sc">$</span>data.clust<span class="sc">$</span>Marital_Status)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   
    Divorced Married Single Together Widow
  1      100     409    231      274    27
  2       68     216    101      142    24
  3       59     227    144      157    26</code></pre>
</div>
</div>
<p>Le statut marital ne semble pas avoir de lien significatif avec nos clusters.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(res.hcpc<span class="sc">$</span>data.clust<span class="sc">$</span>clust,res.hcpc<span class="sc">$</span>data.clust<span class="sc">$</span>Education)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   
    Basic Graduation Master PhD
  1    47        513    280 201
  2     2        254    136 159
  3     0        345    148 120</code></pre>
</div>
</div>
</section>
<section id="lien-entre-les-cluster-et-les-variable-quantitatives" class="level4">
<h4 class="anchored" data-anchor-id="lien-entre-les-cluster-et-les-variable-quantitatives">Lien entre les cluster et les variable quantitatives</h4>
<p>Les deux variables les plus liées à la variable “cluster” sont la dépense totale de chaque client et le score qui est pour rappel le pourcentage du salaire dépensé dans le magasin par chaque client.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggboxplot</span>(res.hcpc<span class="sc">$</span>data.clust, <span class="at">x =</span> <span class="st">"clust"</span>, <span class="at">y =</span> <span class="st">"Montant"</span>,<span class="at">xlab=</span><span class="st">"Cluster"</span>,<span class="at">ylab=</span><span class="st">"Dépense Totale"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projetada_files/figure-html/unnamed-chunk-41-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggboxplot</span>(res.hcpc<span class="sc">$</span>data.clust, <span class="at">x =</span> <span class="st">"clust"</span>, <span class="at">y =</span> <span class="st">"Score"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projetada_files/figure-html/unnamed-chunk-42-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Toutes les variables liées aux achats et aux dépenses présentent le même profil (voir [Analyse graphique]). Cela montre que le cluster 1 regroupe les clients dépensant peu et faisant peu d’achats. Le cluster 2 est celui des clients moyens et le cluster 3 est celui des individus qui dépensent le plus et le plus souvent.</p>
<p>Le vin est un bon exemple qui suit le même schéma que les deux variables Montant et Score. (voir</p>
<p>Cependant, la différence du nombre total d’achat est moins grande entre les cluster 2 et 3 qu’entre le cluster 1 et les autres cluster.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggboxplot</span>(res.hcpc<span class="sc">$</span>data.clust, <span class="at">x =</span> <span class="st">"clust"</span>, <span class="at">y =</span> <span class="st">"Fréquence"</span>,<span class="at">xlab=</span><span class="st">"Cluster"</span>,<span class="at">ylab=</span><span class="st">"Fréquence"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projetada_files/figure-html/unnamed-chunk-43-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Si nous nous intéressons au revenu, qui n’a pas été utilisé dans l’algorithme de clustering, on trouve un résultat cohérent avec les dépenses de chaque cluster. Le cluster 1 regroupe les individus touchant un revenu plus faible. Le cluster 2 est celui des clients avec un revenu moyen tandis que le cluster 3 regroupe les individus plus aisés mais ne contient pas le client le plus aisé. En effet, nous remarquons deux valeurs extrêmes pour le revenu dans le cluster 1.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(res.hcpc<span class="sc">$</span>data.clust<span class="sc">$</span>clust, res.hcpc<span class="sc">$</span>data.clust<span class="sc">$</span>Income, </span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Cluster"</span>, </span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Income"</span>)</span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-5"><a href="#cb80-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-6"><a href="#cb80-6" aria-hidden="true" tabindex="-1"></a><span class="fu">identify</span>(res.hcpc<span class="sc">$</span>data.clust<span class="sc">$</span>clust, res.hcpc<span class="sc">$</span>data.clust<span class="sc">$</span>Income, <span class="at">n =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projetada_files/figure-html/unnamed-chunk-44-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>integer(0)</code></pre>
</div>
</div>
<p>Ces deux valeurs extrêmes sont les cliens 607 et 1279.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>data[<span class="fu">c</span>(<span class="dv">607</span>,<span class="dv">1279</span>),]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Age Education Marital_Status Income Kidhome Teenhome Recency Wine Fruits
607   48       PhD       Together 162397       1        1      31   85      1
1279  53    Master       Together 157733       1        0      37   39      1
     Meat Fish Sweets Gold NumDealsPurchases NumWebPurchases
607    16    2      1    2                 0               0
1279    9    2      0    8                 0               1
     NumCatalogPurchases NumStorePurchases NumWebVisitsMonth AcceptedCmp3
607                    0                 1                 1           No
1279                   0                 1                 1           No
     AcceptedCmp4 AcceptedCmp5 AcceptedCmp1 AcceptedCmp2 Montant Fréquence
607            No           No           No           No     107         1
1279           No           No           No           No      59         2
     Moyenne      Score
607    107.0 0.06588792
1279    29.5 0.03740498</code></pre>
</div>
</div>
<p>Nous remarquons que ces deux clients ont très peu dépensé malgré leur salaire élevé. Ils ont donc un score très faible.</p>
</section>
<section id="analyse-graphique" class="level4">
<h4 class="anchored" data-anchor-id="analyse-graphique"><strong>Analyse graphique</strong></h4>
<p>Les deux graphiques suivants produisent un résumé pour quelques variables en fonction du cluster :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a>res.dc <span class="ot">&lt;-</span> <span class="fu">catdes</span>(res.hcpc<span class="sc">$</span>data.clust, <span class="at">num.var =</span> <span class="dv">28</span>, <span class="at">proba =</span> <span class="fl">0.05</span>)</span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(res.dc, <span class="at">show=</span><span class="st">"all"</span>, <span class="at">output =</span> <span class="st">"figure"</span>, <span class="at">barplot =</span> T, <span class="at">cex.names =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projetada_files/figure-html/unnamed-chunk-46-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projetada_files/figure-html/unnamed-chunk-46-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot.catdes</span>(<span class="fu">catdes</span>(res.hcpc<span class="sc">$</span>data.clust,<span class="dv">28</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projetada_files/figure-html/unnamed-chunk-47-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="lien-avec-quelques-variables-quantitatives" class="level4">
<h4 class="anchored" data-anchor-id="lien-avec-quelques-variables-quantitatives"><strong>Lien avec quelques variables quantitatives</strong></h4>
<p>L’âge est une variable peu liée aux clusters. Nous remarquons que l’âge moyen est un peu plus élevé dans le deuxième cluster.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggboxplot</span>(res.hcpc<span class="sc">$</span>data.clust, <span class="at">x =</span> <span class="st">"clust"</span>, <span class="at">y =</span> <span class="st">"Age"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projetada_files/figure-html/unnamed-chunk-48-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>La variable Recency ne semble pas liée du tout à notre classification :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggboxplot</span>(res.hcpc<span class="sc">$</span>data.clust, <span class="at">x =</span> <span class="st">"clust"</span>, <span class="at">y =</span> <span class="st">"Recency"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projetada_files/figure-html/unnamed-chunk-49-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Les clients les plus friands d’articles en promotion sont ceux du cluster 2 bien qu’ils ne soient pas les moins aisés ni ceux achetant le plus grand nombre d’articles. Nous constatons que les clients du cluster 3, qui ont le plus gros revenu ne sont pas intéressés par des réductions bien qu’ils aient accepté plus que les autres les campagnes 1 et 5.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggboxplot</span>(res.hcpc<span class="sc">$</span>data.clust, <span class="at">x =</span> <span class="st">"clust"</span>, <span class="at">y =</span> <span class="st">"NumDealsPurchases"</span>,<span class="at">xlab=</span><span class="st">"cluster"</span>,<span class="at">ylab=</span><span class="st">""</span>,<span class="at">title =</span> <span class="st">"Nombre d'articles achetés en promotion"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projetada_files/figure-html/unnamed-chunk-50-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="utilisation-du-site-internet-par-les-différents-clusters" class="level4">
<h4 class="anchored" data-anchor-id="utilisation-du-site-internet-par-les-différents-clusters"><strong>Utilisation du site internet par les différents clusters</strong></h4>
<p>Le cluster le plus jeune (le cluster 1) est bien celui effectuant le plus de visites sur le site du magasin. Le cluster le plus âgé, c’est-à-dire le deuxième, est néanmoins en deuxième position. Quant au cluster 3, il consulte peu le site.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggboxplot</span>(res.hcpc<span class="sc">$</span>data.clust, <span class="at">x =</span> <span class="st">"clust"</span>, <span class="at">y =</span> <span class="st">"NumWebVisitsMonth"</span>,<span class="at">xlab=</span><span class="st">"cluster"</span>,<span class="at">ylab=</span><span class="st">""</span>,<span class="at">title=</span><span class="st">"Nombre de visites sur le site internet par mois"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projetada_files/figure-html/unnamed-chunk-51-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggboxplot</span>(res.hcpc<span class="sc">$</span>data.clust, <span class="at">x =</span> <span class="st">"clust"</span>, <span class="at">y =</span> <span class="st">"NumWebPurchases"</span>,<span class="at">title =</span> <span class="st">"Nombre d'achats effectués par internet"</span>,<span class="at">xlab=</span><span class="st">"Cluster"</span>,<span class="at">ylab=</span><span class="st">""</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projetada_files/figure-html/unnamed-chunk-52-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Paradoxalement, le premier cluster est celui effectuant le moins d’achat par internet malgré un important nombre de visites : le taux de conversion est donc mauvais pour ce cluster et il s’agit donc d’une piste à explorer.</p>
</section>
<section id="exemple-du-vin" class="level4">
<h4 class="anchored" data-anchor-id="exemple-du-vin">Exemple du vin</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggboxplot</span>(res.hcpc<span class="sc">$</span>data.clust, <span class="at">x=</span><span class="st">"clust"</span>, <span class="at">y=</span><span class="st">"Wine"</span>,<span class="at">xlab=</span><span class="st">"cluster"</span>,<span class="at">ylab=</span><span class="st">"€"</span>,<span class="at">title=</span><span class="st">"Montant dépensé pour du vin"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projetada_files/figure-html/unnamed-chunk-53-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a>res.hcpc<span class="sc">$</span>data.clust<span class="sc">$</span>wineoverincome <span class="ot">&lt;-</span> <span class="dv">100</span><span class="sc">*</span>data<span class="sc">$</span>Wine<span class="sc">/</span>data<span class="sc">$</span>Income</span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-3"><a href="#cb92-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggboxplot</span>(res.hcpc<span class="sc">$</span>data.clust, <span class="at">x =</span> <span class="st">"clust"</span>, <span class="at">y =</span> <span class="st">"wineoverincome"</span>, <span class="at">title =</span> <span class="st">"Pourcentage du salaire dépensé pour du vin"</span>, <span class="at">xlab =</span> <span class="st">"cluster"</span>,<span class="at">ylab=</span><span class="st">"%"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projetada_files/figure-html/unnamed-chunk-54-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Nous remarquons que le pourcentage du revenu dépensé dans le vin par les clients (qui est le premier poste de revenu du magasin) est très faible dans le cluster 1, cela s’explique par le faible revenu qui caractérise ce cluster. Les individus qui font partie du cluster 1 vont donc privilégier des postes de dépense plus essentiels. Au contraire, les clients des cluster 2 et 3 dépense sensiblement le même pourcentage de leur revenu pour du vin. Une piste d’opération marketing serait de cibler les clients du cluster 3 car plus aisés et donc plus à même d’augmenter cette part de dépense dans leur budget.</p>
</section>
</section>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>L’analyse des données a permis de séparer la clientèle du supermarché en trois groupes distincts, chacun présentant des différences significatives en termes de dépenses, de fréquence d’achat et de profil socio-économique. Ces groupes constituent une base très utile pour l’élaboration de stratégies de marketing optimisées et ciblées. Par exemple, les clients du groupe 3 sont plus aisés et sont prêts à dépenser plus d’argent, ils devraient donc être prioritaires pour les offres haut de gamme. De même, des actions spécifiques pourraient être envisagées pour inciter les clients des groupes 1 et 2 à augmenter leur panier moyen.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>